[package]
name = "fluent-bug-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent = "0.16.0"
unic-langid = {version = "0.9.1", features = ["macros"]}